spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/spring_ddd"
    driverClassName: com.mysql.jdbc.Driver
    username: "root"
    password: ""
    min-idle: 1
    max-idle: 1
    max-active: 2
    initial-size: 1
    validation-query: "SELECT 1"
    test-on-borrow: true
